language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - mkdir -p build/logs

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi;'

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then CODECLIMATE_REPO_TOKEN=b80ba7cc0a0c40f2f76e986e88b7b4e817d48298934863e160b43ed00b46f862 ./vendor/bin/test-reporter; fi;'

notifications:
  slack:
    rooms:
      secure: L/2t/CQMDz+fvWxFlE8SEHcTJRBJJrv8fwN1ba0cs0+0M7iGe7ZFmmJF8o8WhFQGUD0wnl0r7Z5BhWMnCPLWCHwuy3O5QEWbAmOXoYhYNY8RR/NEW3Zjbffyy5RW04TjO9gZ5fi5uR9IFxKb82HAZ823QJ/2FOwLsycY2fh1vfYns7GYblcv9U+gh5NbPwCA8F09nfDh0qyWQWf5BoLlNbpVI7vPVoyNvTiuf26xnhoDByU3q1YRQ+y5kMnj5ou1h+ugyuDQVzJhMxSATNSbvYDFu6LHdPhHN48yQgTdfMzm0wZiZxL2nNjxq9Pb0UY1ufrgIjdl/1CkTwCizjsitW+acm9T+RCCpMbZg/0Z2rUB5gqncCWvaUwULslRYZSxjqUlfPuX6h6gottOvIjMpIL+160RU8c2cnNsyR0W/Q7QDKtHuwxgT+OooBWWXbtRVujCj7RvNlmzvP037ktcQyAbeo54yPKQ9sFiHjYO/3F8KIuevoDWqXMa6f6+bdKwMnLVphjaXd7X4HwOLnVApWFmVQ0CbtupUo5YbkzsNp1WMnEd9b12kVFc6D1EYHWz/Ns7VLw1dJonYJOx4+IrUw8RqrdDVBDnb1h3PKMTDRnPujKyg+ZLIHTwObO9Em2z3wwn7ftHHzcQ+V+Rn5c1J8bn2vhxZqdAyAo7EVWtXf8=
